import React from "react";
import Head from "next/head";

import NavBar from "./Components/NavBar";
import SideBar from "./Components/SideBar";
import AddActressContainer from "./Components/AddActressContainer";

const AddActress = () => {
  return (
    <div>
      <Head>
        <title>Add Actress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <SideBar pathname={"category"} />
        <RightSideContainer>
          <NavBar />
          <AddActressContainer />
        </RightSideContainer>
      </MainContainer>
    </div>
  );
};

const MainContainer = (props) => (
  <div className="flex flex-row">{props.children}</div>
);

const RightSideContainer = (props) => (
  <div className="w-full flex flex-col">{props.children} </div>
);

export default AddActress;
